In [10]:
import numpy as np

In [3]:
arr = np.array([5,7,6,8,9,88,99])
type(arr)

numpy.ndarray

In [4]:
arr**.5

array([2.23606798, 2.64575131, 2.44948974, 2.82842712, 3.        ,
       9.38083152, 9.94987437])

In [5]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr[:,0:1]

array([[1],
       [4],
       [7]])

In [8]:
arr[2:,:]

array([[7, 8, 9]])

In [14]:
arr2 = np.arange(0,10,.5)
arr2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [16]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
z = np.zeros(4)

In [18]:
z

array([0., 0., 0., 0.])

In [19]:
o1 = np.ones(5)
o2 = np.ones((5,4))
o1
o2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
o1

array([1., 1., 1., 1., 1.])

In [21]:
o2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# linspace

return evenly spaced numbers over a specified interval

In [22]:
L = np.linspace(1,25,9)
L

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25.])

In [23]:
L3 = L.reshape(3,3)
L3

array([[ 1.,  4.,  7.],
       [10., 13., 16.],
       [19., 22., 25.]])

In [24]:
import random
arr = np.random.rand(3,4)
arr

array([[0.94687169, 0.95700875, 0.75593755, 0.03745511],
       [0.4158748 , 0.58274232, 0.25072454, 0.01334787],
       [0.18274845, 0.74561294, 0.61114256, 0.05815833]])

In [25]:
from numpy.random import rand
arr_simp = rand(3,4)
arr_simp

array([[0.1399513 , 0.74486302, 0.19840979, 0.70473292],
       [0.92970348, 0.52027975, 0.40351867, 0.83008583],
       [0.48812914, 0.59095977, 0.45987738, 0.27958191]])

# randn

return a sample (or samples) from the 'standard normal' distribution; not uniform like rand

In [26]:
from numpy.random import randn
mat = randn(3,2)
mat

array([[ 0.81181359, -0.91986003],
       [-0.4245504 ,  0.41914226],
       [ 2.68557172,  0.22200826]])